###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
	"name":"Guilherme de Oliveira",
	"email":"guilhermecomercial51@gmail.com",
	"password":"123456",
	"role":"ADMIN"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
	"email":"guilhermecomercial51@gmail.com",
	"password":"123456"
}

###
POST http://localhost:3003/pizza/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlYjYyYjI5LTAwNTAtNGFmYy1hMjFlLTUwNmVhZDgxMGQyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1ODAyMDI1MiwiZXhwIjoxNjU4MDIzODUyfQ.Fsq9rD8XLbOWCVb7TCz4XObXS0N29Oc1ha6kEEnHjok
Content-Type: application/json

{
	"name":"Baiana",
	"price":10.0,
	"imgUrl":"https://www.receitasdecomida.com.br/wp-content/uploads/2013/09/pizza-baiana-rapida-6428.jpg",
	"ingredients":"1 pitada de pimenta do reino,1 pitada sal,1 unidade massa de pizza,2 unidades de ovos,3 unidades linguiça de porco,3 unidades tomate,200 gramas queijo mozzarela"

}

###
POST http://localhost:3003/item/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlYjYyYjI5LTAwNTAtNGFmYy1hMjFlLTUwNmVhZDgxMGQyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1ODcxNjQ1MywiZXhwIjoxNjU4NzIwMDUzfQ.pqBc43pPG8O8Don75lxmLn49iI58dz_vygp5EfKPX7I
Content-Type: application/json

{
	"pizzaId":"95f57823-1fb8-48e8-aa8c-339a2d5a26aa",
	"quantity":2
}

###
POST http://localhost:3003/order/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlYjYyYjI5LTAwNTAtNGFmYy1hMjFlLTUwNmVhZDgxMGQyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1ODcxNjQ1MywiZXhwIjoxNjU4NzIwMDUzfQ.pqBc43pPG8O8Don75lxmLn49iI58dz_vygp5EfKPX7I
Content-Type: application/json

{
	"orderId":"da3c5688-9027-426e-9919-944be474fe31"
	
}

###
GET http://localhost:3003/pizza/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlYjYyYjI5LTAwNTAtNGFmYy1hMjFlLTUwNmVhZDgxMGQyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1ODI2OTgyMiwiZXhwIjoxNjU4MjczNDIyfQ.LvO0jo07jwlnDCYiEOV3qmWymaAH-t_jEDQzMh_AOO4

###
GET http://localhost:3003/order/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlYjYyYjI5LTAwNTAtNGFmYy1hMjFlLTUwNmVhZDgxMGQyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1ODcyNTA5MCwiZXhwIjoxNjU4NzI4NjkwfQ.GvmNcUeauoEbipcC1psA7p877cjkVL_UrtSK2y93lb8

###
GET http://localhost:3003/pizza/95f57823-1fb8-48e8-aa8c-339a2d5a26aa
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlYjYyYjI5LTAwNTAtNGFmYy1hMjFlLTUwNmVhZDgxMGQyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1ODQ1MTAyMywiZXhwIjoxNjU4NDU0NjIzfQ.4TVvGjZM3r-eQ8TtrBd2M_rGGU3bd4jWMhI8pRsUZEA

###
GET http://localhost:3003/item/cart
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlYjYyYjI5LTAwNTAtNGFmYy1hMjFlLTUwNmVhZDgxMGQyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1ODY4MjY4MiwiZXhwIjoxNjU4Njg2MjgyfQ.hcvUvYTimEpGENDD533gX1sVlqdx4BtOe7DG7lNmG4o

###
DELETE http://localhost:3003/item/delete/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlYjYyYjI5LTAwNTAtNGFmYy1hMjFlLTUwNmVhZDgxMGQyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1ODYzMjkwMiwiZXhwIjoxNjU4NjM2NTAyfQ.dKy8uUICQKyzPFDXokpvikYxJ3sGi1UaJ0YuodsLUrc

###
GET http://localhost:3003/order/details/da3c5688-9027-426e-9919-944be474fe31
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlYjYyYjI5LTAwNTAtNGFmYy1hMjFlLTUwNmVhZDgxMGQyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1ODc3MTczNiwiZXhwIjoxNjU4Nzc1MzM2fQ._8JaqWBipyePb0eJ8qzMWS8E4QV-EPDufO8rQbefezA